version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 20
  pre_build:
    commands:
      - echo "Installing dependencies..."
      - npm ci
  build:
    commands:
      - echo "Building NestJS app..."
      - npm run build

artifacts:
  files:
    - 'dist/**/*'
    - package.json
    - package-lock.json
    - Procfile
  discard-paths: no
